const sourcePoliticalStance = {
  // Left-leaning
  Wired: "left",
  "Gizmodo.com": "left",
  "BBC News": "left",
  Time: "left",
  Kotaku: "left",
  NPR: "left",
  Buzzfeed: "left",
  CNN: "left",
  MSNBC: "left",
  "MTV News": "left",
  "Vice News": "left",
  "The Huffington Post": "left",
  "New York Magazine": "left",
  "The Washington Post": "left",
  Variety: "left",
  "ABC News": "left",
  Politico: "left",
  "Yahoo Entertainment": "left",

  // Right-leaning
  "The Verge": "right",
  "Al Jazeera English": "right",
  InfoMoney: "right",
  "The Wall Street Journal": "right",
  "Breitbart News": "right",
  "Fox News": "right",
  "Fox Sports": "right",
  "National Review": "right",
  "The American Conservative": "right",
  "One America News Network": "right",
  "Rebel News": "right",
  RealClearPolitics: "right",
  "The Sun": "right",
  "The Daily Telegraph": "right",
  "Associated Press": "right",
  "Livenowfox.com": "right",
  ScienceAlert: "right",
  Axios: "right",
};

export default sourcePoliticalStance;
